name: Update Data
on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # Or manually from GitHub UI

jobs:
  autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master

    # Set-up R
    - name: Install packages
      run: |
        R -e 'install.packages("rjson")'
        R -e 'install.packages("dplyr")'

    - name: Check for existing branch
      run: |
        if [[ $(git ls-remote --heads origin refs/heads/data-update | wc -l) == "1" ]]; then
          echo deleting existing branch
          git push origin --delete data-update
        else
          echo no existing branch found
        fi

    - name: Update data
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git branch data-update
        git checkout data-update
        source("Scripts/auto-update.R")
      shell: Rscript {0}

    - name: Commit, push and open new PR with changes (if any)
      run: |
        if [[ `git status --porcelain` ]]; then
          git commit -a -m 'data update'
          git push --set-upstream origin data-update
          gh pr create -B master -H data-update --title 'Automated data update' --body 'Automated Data Update'
        else
          echo No auction changes detected, skipping update.
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





